export const PROVINCES = [
  "Agadir-Ida-Ou-Tanane",
  "Al Haouz",
  "Al Hoceïma",
  "Aousserd",
  "Assa-Zag",
  "Azilal",
  "Béni Mellal",
  "Benslimane",
  "Berkane",
  "Berrechid",
  "Boujdour",
  "Boulemane",
  "Casablanca",
  "Chefchaouen",
  "Chichaoua",
  "Chtouka-Aït Baha",
  "Driouch",
  "El Hajeb",
  "El Jadida",
  "El Kelâa des Sraghna",
  "Errachidia",
  "Es-Semara",
  "Essaouira",
  "Fahs-Anjra",
  "Fès",
  "Figuig",
  "Guelmim",
  "Guercif",
  "Ifrane",
  "Inezgane-Aït Melloul",
  "Jerada",
  "Kénitra",
  "Khémisset",
  "Khénifra",
  "Khouribga",
  "Laâyoune",
  "Larache",
  "Marrakech",
  "Médiouna",
  "Meknès",
  "Midelt",
  "Mohammadia",
  "Moulay Yacoub",
  "Nador",
  "Nouaceur",
  "Ouarzazate",
  "Oued Ed-Dahab",
  "Oujda-Angad",
  "Rabat",
  "Rehamna",
  "Safi",
  "Salé",
  "Sefrou",
  "Settat",
  "Sidi Bennour",
  "Sidi Ifni",
  "Sidi Kacem",
  "Sidi Slimane",
  "Skhirate-Témara",
  "Tanger-Assilah",
  "Tan-Tan",
  "Taounate",
  "Taourirt",
  "Tarfaya",
  "Taroudannt",
  "Tata",
  "Taza",
  "Tétouan",
  "Tinghir",
  "Tiznit",
  "Youssoufia",
  "Zagora",
];
